YEARS = [str(y) for y in range(2026, 1989, -1)]

VEHICLE_DATA = {
    "Acura": {
        "ILX": ["2.4L 4-Cyl", "1.5L Turbo 4-Cyl"],
        "Integra": ["1.5L Turbo 4-Cyl"],
        "MDX": ["3.5L V6", "3.0L Turbo V6", "3.0L Turbo V6 Hybrid"],
        "RDX": ["2.0L Turbo 4-Cyl"],
        "TLX": ["2.0L Turbo 4-Cyl", "3.0L Turbo V6"],
        "TSX": ["2.4L 4-Cyl", "3.5L V6"],
    },
    "Alfa Romeo": {
        "Giulia": ["2.0L Turbo 4-Cyl", "2.9L Twin-Turbo V6"],
        "Stelvio": ["2.0L Turbo 4-Cyl", "2.9L Twin-Turbo V6"],
    },
    "Audi": {
        "A3": ["2.0L Turbo 4-Cyl", "1.4L Turbo 4-Cyl"],
        "A4": ["2.0L Turbo 4-Cyl", "3.0L Turbo V6"],
        "A5": ["2.0L Turbo 4-Cyl", "3.0L Turbo V6"],
        "A6": ["2.0L Turbo 4-Cyl", "3.0L Turbo V6"],
        "A7": ["3.0L Turbo V6", "2.0L Turbo 4-Cyl"],
        "A8": ["3.0L Turbo V6", "4.0L Twin-Turbo V8"],
        "Q3": ["2.0L Turbo 4-Cyl"],
        "Q5": ["2.0L Turbo 4-Cyl", "3.0L Turbo V6"],
        "Q7": ["2.0L Turbo 4-Cyl", "3.0L Turbo V6"],
        "Q8": ["3.0L Turbo V6", "4.0L Twin-Turbo V8"],
        "e-tron": ["Electric"],
        "RS5": ["2.9L Twin-Turbo V6"],
        "S4": ["3.0L Turbo V6"],
        "TT": ["2.0L Turbo 4-Cyl"],
    },
    "BMW": {
        "2 Series": ["2.0L Turbo 4-Cyl", "3.0L Turbo 6-Cyl"],
        "3 Series": ["2.0L Turbo 4-Cyl", "3.0L Turbo 6-Cyl", "2.0L Diesel"],
        "4 Series": ["2.0L Turbo 4-Cyl", "3.0L Turbo 6-Cyl"],
        "5 Series": ["2.0L Turbo 4-Cyl", "3.0L Turbo 6-Cyl", "4.4L Twin-Turbo V8"],
        "7 Series": ["3.0L Turbo 6-Cyl", "4.4L Twin-Turbo V8"],
        "X1": ["2.0L Turbo 4-Cyl"],
        "X3": ["2.0L Turbo 4-Cyl", "3.0L Turbo 6-Cyl"],
        "X5": ["3.0L Turbo 6-Cyl", "4.4L Twin-Turbo V8", "3.0L Diesel"],
        "X7": ["3.0L Turbo 6-Cyl", "4.4L Twin-Turbo V8"],
        "i4": ["Electric"],
        "iX": ["Electric"],
        "M3": ["3.0L Twin-Turbo 6-Cyl"],
        "M4": ["3.0L Twin-Turbo 6-Cyl"],
        "M5": ["4.4L Twin-Turbo V8"],
    },
    "Buick": {
        "Enclave": ["3.6L V6"],
        "Encore": ["1.4L Turbo 4-Cyl"],
        "Encore GX": ["1.2L Turbo 3-Cyl", "1.3L Turbo 3-Cyl"],
        "Envision": ["2.0L Turbo 4-Cyl"],
    },
    "Cadillac": {
        "CT4": ["2.0L Turbo 4-Cyl", "2.7L Turbo 4-Cyl"],
        "CT5": ["2.0L Turbo 4-Cyl", "3.0L Twin-Turbo V6"],
        "Escalade": ["6.2L V8", "3.0L Diesel 6-Cyl"],
        "XT4": ["2.0L Turbo 4-Cyl"],
        "XT5": ["2.0L Turbo 4-Cyl", "3.6L V6"],
        "XT6": ["2.0L Turbo 4-Cyl", "3.6L V6"],
        "LYRIQ": ["Electric"],
    },
    "Chevrolet": {
        "Blazer": ["2.0L Turbo 4-Cyl", "3.6L V6", "Electric"],
        "Camaro": ["2.0L Turbo 4-Cyl", "3.6L V6", "6.2L V8"],
        "Colorado": ["2.7L Turbo 4-Cyl", "3.6L V6", "2.8L Diesel"],
        "Corvette": ["6.2L V8", "5.5L V8"],
        "Equinox": ["1.5L Turbo 4-Cyl", "2.0L Turbo 4-Cyl", "Electric"],
        "Malibu": ["1.5L Turbo 4-Cyl", "2.0L Turbo 4-Cyl"],
        "Silverado 1500": ["2.7L Turbo 4-Cyl", "5.3L V8", "6.2L V8", "3.0L Diesel"],
        "Silverado 2500HD": ["6.6L V8", "6.6L Diesel V8"],
        "Suburban": ["5.3L V8", "6.2L V8", "3.0L Diesel"],
        "Tahoe": ["5.3L V8", "6.2L V8", "3.0L Diesel"],
        "Traverse": ["3.6L V6"],
        "Trailblazer": ["1.2L Turbo 3-Cyl", "1.3L Turbo 3-Cyl"],
        "Bolt EV": ["Electric"],
        "Bolt EUV": ["Electric"],
        "Impala": ["2.5L 4-Cyl", "3.6L V6"],
        "Cruze": ["1.4L Turbo 4-Cyl", "1.6L Diesel"],
        "Spark": ["1.4L 4-Cyl"],
    },
    "Chrysler": {
        "300": ["3.6L V6", "5.7L HEMI V8"],
        "Pacifica": ["3.6L V6", "3.6L V6 Hybrid"],
        "Voyager": ["3.6L V6"],
    },
    "Dodge": {
        "Challenger": ["3.6L V6", "5.7L HEMI V8", "6.2L Supercharged V8", "6.4L V8"],
        "Charger": ["3.6L V6", "5.7L HEMI V8", "6.2L Supercharged V8", "6.4L V8"],
        "Durango": ["3.6L V6", "5.7L HEMI V8", "6.4L V8"],
        "Hornet": ["2.0L Turbo 4-Cyl", "1.3L Turbo Hybrid"],
        "Ram 1500": ["3.6L V6", "5.7L HEMI V8", "3.0L EcoDiesel V6"],
        "Ram 2500": ["6.4L HEMI V8", "6.7L Cummins Diesel"],
        "Ram 3500": ["6.4L HEMI V8", "6.7L Cummins Diesel"],
    },
    "Ford": {
        "Bronco": ["2.3L Turbo 4-Cyl", "2.7L Twin-Turbo V6"],
        "Bronco Sport": ["1.5L Turbo 3-Cyl", "2.0L Turbo 4-Cyl"],
        "Edge": ["2.0L Turbo 4-Cyl"],
        "Escape": ["1.5L Turbo 3-Cyl", "2.0L Turbo 4-Cyl", "2.5L Hybrid"],
        "Expedition": ["3.5L Twin-Turbo V6"],
        "Explorer": ["2.3L Turbo 4-Cyl", "3.0L Twin-Turbo V6", "3.3L Hybrid"],
        "F-150": ["2.7L Twin-Turbo V6", "3.5L Twin-Turbo V6", "5.0L V8", "3.0L Diesel", "3.5L Hybrid"],
        "F-250": ["6.2L V8", "7.3L V8", "6.7L Diesel V8"],
        "F-350": ["6.2L V8", "7.3L V8", "6.7L Diesel V8"],
        "Fusion": ["1.5L Turbo 4-Cyl", "2.0L Turbo 4-Cyl", "2.5L Hybrid"],
        "Maverick": ["2.0L Turbo 4-Cyl", "2.5L Hybrid"],
        "Mustang": ["2.3L Turbo 4-Cyl", "5.0L V8", "5.2L V8"],
        "Ranger": ["2.3L Turbo 4-Cyl"],
        "Transit": ["3.5L V6", "3.5L Twin-Turbo V6"],
        "Mustang Mach-E": ["Electric"],
        "F-150 Lightning": ["Electric"],
        "Focus": ["2.0L 4-Cyl", "1.0L Turbo 3-Cyl", "2.3L Turbo 4-Cyl"],
        "Taurus": ["2.0L Turbo 4-Cyl", "3.5L V6"],
    },
    "Genesis": {
        "G70": ["2.0L Turbo 4-Cyl", "3.3L Twin-Turbo V6"],
        "G80": ["2.5L Turbo 4-Cyl", "3.5L Twin-Turbo V6"],
        "G90": ["3.5L Twin-Turbo V6"],
        "GV70": ["2.5L Turbo 4-Cyl", "3.5L Twin-Turbo V6"],
        "GV80": ["2.5L Turbo 4-Cyl", "3.5L Twin-Turbo V6"],
    },
    "GMC": {
        "Acadia": ["2.0L Turbo 4-Cyl", "3.6L V6"],
        "Canyon": ["2.7L Turbo 4-Cyl", "3.6L V6"],
        "Sierra 1500": ["2.7L Turbo 4-Cyl", "5.3L V8", "6.2L V8", "3.0L Diesel"],
        "Sierra 2500HD": ["6.6L V8", "6.6L Diesel V8"],
        "Terrain": ["1.5L Turbo 4-Cyl"],
        "Yukon": ["5.3L V8", "6.2L V8", "3.0L Diesel"],
        "HUMMER EV": ["Electric"],
    },
    "Honda": {
        "Accord": ["1.5L Turbo 4-Cyl", "2.0L Turbo 4-Cyl", "2.0L Hybrid"],
        "Civic": ["2.0L 4-Cyl", "1.5L Turbo 4-Cyl", "2.0L Turbo 4-Cyl"],
        "CR-V": ["1.5L Turbo 4-Cyl", "2.0L Hybrid"],
        "HR-V": ["2.0L 4-Cyl"],
        "Odyssey": ["3.5L V6"],
        "Passport": ["3.5L V6"],
        "Pilot": ["3.5L V6", "2.0L Turbo Hybrid"],
        "Ridgeline": ["3.5L V6"],
        "Fit": ["1.5L 4-Cyl"],
        "Prologue": ["Electric"],
    },
    "Hyundai": {
        "Accent": ["1.6L 4-Cyl"],
        "Elantra": ["2.0L 4-Cyl", "1.6L Turbo 4-Cyl", "1.6L Hybrid"],
        "Ioniq 5": ["Electric"],
        "Ioniq 6": ["Electric"],
        "Kona": ["2.0L 4-Cyl", "1.6L Turbo 4-Cyl", "Electric"],
        "Palisade": ["3.8L V6"],
        "Santa Cruz": ["2.5L 4-Cyl", "2.5L Turbo 4-Cyl"],
        "Santa Fe": ["2.5L 4-Cyl", "2.5L Turbo 4-Cyl", "1.6L Turbo Hybrid"],
        "Sonata": ["2.5L 4-Cyl", "1.6L Turbo 4-Cyl", "2.0L Turbo 4-Cyl"],
        "Tucson": ["2.5L 4-Cyl", "1.6L Turbo Hybrid"],
        "Veloster": ["2.0L 4-Cyl", "1.6L Turbo 4-Cyl"],
    },
    "Infiniti": {
        "Q50": ["3.0L Twin-Turbo V6"],
        "Q60": ["3.0L Twin-Turbo V6"],
        "QX50": ["2.0L Turbo 4-Cyl"],
        "QX55": ["2.0L Turbo 4-Cyl"],
        "QX60": ["3.5L V6"],
        "QX80": ["5.6L V8"],
    },
    "Jaguar": {
        "E-PACE": ["2.0L Turbo 4-Cyl"],
        "F-PACE": ["2.0L Turbo 4-Cyl", "3.0L Supercharged V6", "5.0L Supercharged V8"],
        "F-TYPE": ["2.0L Turbo 4-Cyl", "5.0L Supercharged V8"],
        "XE": ["2.0L Turbo 4-Cyl"],
        "XF": ["2.0L Turbo 4-Cyl", "3.0L Supercharged V6"],
        "I-PACE": ["Electric"],
    },
    "Jeep": {
        "Cherokee": ["2.4L 4-Cyl", "3.2L V6", "2.0L Turbo 4-Cyl"],
        "Compass": ["2.4L 4-Cyl", "2.0L Turbo 4-Cyl"],
        "Gladiator": ["3.6L V6", "3.0L EcoDiesel V6"],
        "Grand Cherokee": ["3.6L V6", "5.7L HEMI V8", "2.0L Turbo 4xe Hybrid", "6.4L V8"],
        "Renegade": ["1.3L Turbo 4-Cyl", "2.4L 4-Cyl"],
        "Wrangler": ["3.6L V6", "2.0L Turbo 4-Cyl", "3.0L EcoDiesel V6", "6.4L V8"],
        "Wagoneer": ["3.0L Twin-Turbo 6-Cyl", "6.4L V8"],
        "Grand Wagoneer": ["3.0L Twin-Turbo 6-Cyl", "6.4L V8"],
    },
    "Kia": {
        "Carnival": ["3.5L V6"],
        "EV6": ["Electric"],
        "Forte": ["2.0L 4-Cyl", "1.6L Turbo 4-Cyl"],
        "K5": ["1.6L Turbo 4-Cyl", "2.5L 4-Cyl"],
        "Niro": ["1.6L Hybrid", "Electric"],
        "Seltos": ["2.0L 4-Cyl", "1.6L Turbo 4-Cyl"],
        "Sorento": ["2.5L 4-Cyl", "2.5L Turbo 4-Cyl", "1.6L Turbo Hybrid"],
        "Soul": ["2.0L 4-Cyl", "Electric"],
        "Sportage": ["2.5L 4-Cyl", "2.5L Turbo 4-Cyl", "1.6L Turbo Hybrid"],
        "Stinger": ["2.5L Turbo 4-Cyl", "3.3L Twin-Turbo V6"],
        "Telluride": ["3.8L V6"],
    },
    "Land Rover": {
        "Defender": ["2.0L Turbo 4-Cyl", "3.0L Turbo 6-Cyl", "5.0L Supercharged V8"],
        "Discovery": ["3.0L Turbo 6-Cyl"],
        "Discovery Sport": ["2.0L Turbo 4-Cyl"],
        "Range Rover": ["3.0L Turbo 6-Cyl", "4.4L Twin-Turbo V8"],
        "Range Rover Sport": ["3.0L Turbo 6-Cyl", "4.4L Twin-Turbo V8"],
        "Range Rover Evoque": ["2.0L Turbo 4-Cyl"],
        "Range Rover Velar": ["2.0L Turbo 4-Cyl", "3.0L Turbo 6-Cyl"],
    },
    "Lexus": {
        "ES": ["2.5L 4-Cyl", "2.5L Hybrid"],
        "GX": ["4.6L V8", "2.4L Turbo Hybrid"],
        "IS": ["2.0L Turbo 4-Cyl", "3.5L V6"],
        "LC": ["5.0L V8", "3.5L V6 Hybrid"],
        "LX": ["3.5L Twin-Turbo V6"],
        "NX": ["2.5L 4-Cyl", "2.5L Hybrid", "2.5L PHEV"],
        "RC": ["2.0L Turbo 4-Cyl", "3.5L V6"],
        "RX": ["2.4L Turbo 4-Cyl", "2.5L Hybrid"],
        "TX": ["2.4L Turbo 4-Cyl", "2.5L Hybrid"],
        "UX": ["2.0L 4-Cyl", "2.0L Hybrid"],
        "RZ": ["Electric"],
    },
    "Lincoln": {
        "Aviator": ["3.0L Twin-Turbo V6", "3.0L Twin-Turbo V6 PHEV"],
        "Corsair": ["2.0L Turbo 4-Cyl", "2.5L Hybrid"],
        "Nautilus": ["2.0L Turbo 4-Cyl", "2.7L Twin-Turbo V6"],
        "Navigator": ["3.5L Twin-Turbo V6"],
    },
    "Mazda": {
        "CX-30": ["2.5L 4-Cyl", "2.5L Turbo 4-Cyl"],
        "CX-5": ["2.5L 4-Cyl", "2.5L Turbo 4-Cyl"],
        "CX-50": ["2.5L 4-Cyl", "2.5L Turbo 4-Cyl"],
        "CX-70": ["3.3L Turbo 6-Cyl", "2.5L PHEV"],
        "CX-90": ["3.3L Turbo 6-Cyl", "2.5L PHEV"],
        "Mazda3": ["2.5L 4-Cyl", "2.5L Turbo 4-Cyl"],
        "MX-5 Miata": ["2.0L 4-Cyl"],
    },
    "Mercedes-Benz": {
        "A-Class": ["2.0L Turbo 4-Cyl"],
        "C-Class": ["2.0L Turbo 4-Cyl", "3.0L Turbo 6-Cyl"],
        "CLA": ["2.0L Turbo 4-Cyl"],
        "E-Class": ["2.0L Turbo 4-Cyl", "3.0L Turbo 6-Cyl"],
        "GLA": ["2.0L Turbo 4-Cyl"],
        "GLB": ["2.0L Turbo 4-Cyl"],
        "GLC": ["2.0L Turbo 4-Cyl", "3.0L Turbo 6-Cyl"],
        "GLE": ["2.0L Turbo 4-Cyl", "3.0L Turbo 6-Cyl", "4.0L Turbo V8"],
        "GLS": ["3.0L Turbo 6-Cyl", "4.0L Turbo V8"],
        "S-Class": ["3.0L Turbo 6-Cyl", "4.0L Turbo V8"],
        "AMG GT": ["4.0L Twin-Turbo V8"],
        "EQB": ["Electric"],
        "EQE": ["Electric"],
        "EQS": ["Electric"],
    },
    "Mitsubishi": {
        "Eclipse Cross": ["1.5L Turbo 4-Cyl", "2.4L PHEV"],
        "Mirage": ["1.2L 3-Cyl"],
        "Outlander": ["2.5L 4-Cyl", "2.4L PHEV"],
        "Outlander Sport": ["2.0L 4-Cyl", "2.4L 4-Cyl"],
    },
    "Nissan": {
        "Altima": ["2.5L 4-Cyl", "2.0L Turbo 4-Cyl"],
        "Armada": ["5.6L V8"],
        "Frontier": ["3.8L V6"],
        "Kicks": ["1.6L 4-Cyl"],
        "Leaf": ["Electric"],
        "Maxima": ["3.5L V6"],
        "Murano": ["3.5L V6"],
        "Pathfinder": ["3.5L V6"],
        "Rogue": ["1.5L Turbo 3-Cyl", "2.5L 4-Cyl"],
        "Sentra": ["2.0L 4-Cyl"],
        "Titan": ["5.6L V8"],
        "Versa": ["1.6L 4-Cyl"],
        "Z": ["3.0L Twin-Turbo V6"],
        "Ariya": ["Electric"],
    },
    "Porsche": {
        "911": ["3.0L Twin-Turbo Flat-6", "3.7L Twin-Turbo Flat-6", "4.0L Flat-6"],
        "Boxster": ["2.0L Turbo Flat-4", "2.5L Turbo Flat-4"],
        "Cayenne": ["3.0L Turbo V6", "4.0L Twin-Turbo V8", "3.0L V6 Hybrid"],
        "Cayman": ["2.0L Turbo Flat-4", "2.5L Turbo Flat-4", "4.0L Flat-6"],
        "Macan": ["2.0L Turbo 4-Cyl", "2.9L Twin-Turbo V6", "Electric"],
        "Panamera": ["2.9L Twin-Turbo V6", "4.0L Twin-Turbo V8"],
        "Taycan": ["Electric"],
    },
    "Ram": {
        "1500": ["3.6L V6", "5.7L HEMI V8", "3.0L EcoDiesel V6"],
        "2500": ["6.4L HEMI V8", "6.7L Cummins Diesel"],
        "3500": ["6.4L HEMI V8", "6.7L Cummins Diesel"],
        "ProMaster": ["3.6L V6"],
    },
    "Subaru": {
        "Ascent": ["2.4L Turbo Flat-4"],
        "BRZ": ["2.4L Flat-4"],
        "Crosstrek": ["2.0L Flat-4", "2.5L Flat-4", "2.5L Hybrid"],
        "Forester": ["2.5L Flat-4"],
        "Impreza": ["2.0L Flat-4", "2.5L Flat-4"],
        "Legacy": ["2.5L Flat-4", "2.4L Turbo Flat-4"],
        "Outback": ["2.5L Flat-4", "2.4L Turbo Flat-4"],
        "Solterra": ["Electric"],
        "WRX": ["2.4L Turbo Flat-4"],
    },
    "Tesla": {
        "Model 3": ["Electric"],
        "Model S": ["Electric"],
        "Model X": ["Electric"],
        "Model Y": ["Electric"],
        "Cybertruck": ["Electric"],
    },
    "Toyota": {
        "4Runner": ["4.0L V6", "2.4L Turbo Hybrid"],
        "86": ["2.4L Flat-4"],
        "Camry": ["2.5L 4-Cyl", "2.5L Hybrid", "3.5L V6"],
        "Corolla": ["2.0L 4-Cyl", "1.8L Hybrid"],
        "Corolla Cross": ["2.0L 4-Cyl", "2.0L Hybrid"],
        "Crown": ["2.5L Hybrid", "2.4L Turbo Hybrid"],
        "GR86": ["2.4L Flat-4"],
        "GR Supra": ["2.0L Turbo 4-Cyl", "3.0L Turbo 6-Cyl"],
        "Highlander": ["2.5L Hybrid", "3.5L V6", "2.4L Turbo Hybrid"],
        "Land Cruiser": ["2.4L Turbo Hybrid"],
        "Prius": ["1.8L Hybrid", "2.0L Hybrid"],
        "RAV4": ["2.5L 4-Cyl", "2.5L Hybrid", "2.5L PHEV"],
        "Sequoia": ["3.5L Twin-Turbo V6 Hybrid"],
        "Sienna": ["2.5L Hybrid"],
        "Tacoma": ["2.7L 4-Cyl", "3.5L V6", "2.4L Turbo 4-Cyl"],
        "Tundra": ["3.5L Twin-Turbo V6", "3.5L Twin-Turbo V6 Hybrid"],
        "Venza": ["2.5L Hybrid"],
        "bZ4X": ["Electric"],
    },
    "Volkswagen": {
        "Atlas": ["2.0L Turbo 4-Cyl", "3.6L V6"],
        "Atlas Cross Sport": ["2.0L Turbo 4-Cyl", "3.6L V6"],
        "Golf": ["1.4L Turbo 4-Cyl", "2.0L Turbo 4-Cyl"],
        "Golf GTI": ["2.0L Turbo 4-Cyl"],
        "Golf R": ["2.0L Turbo 4-Cyl"],
        "ID.4": ["Electric"],
        "Jetta": ["1.5L Turbo 4-Cyl", "2.0L Turbo 4-Cyl"],
        "Jetta GLI": ["2.0L Turbo 4-Cyl"],
        "Taos": ["1.5L Turbo 4-Cyl"],
        "Tiguan": ["2.0L Turbo 4-Cyl"],
    },
    "Volvo": {
        "S60": ["2.0L Turbo 4-Cyl", "2.0L Turbo/Supercharged 4-Cyl"],
        "S90": ["2.0L Turbo 4-Cyl", "2.0L Turbo/Supercharged 4-Cyl"],
        "V60": ["2.0L Turbo 4-Cyl", "2.0L Turbo/Supercharged 4-Cyl PHEV"],
        "V90": ["2.0L Turbo 4-Cyl"],
        "XC40": ["2.0L Turbo 4-Cyl", "Electric"],
        "XC60": ["2.0L Turbo 4-Cyl", "2.0L Turbo/Supercharged 4-Cyl", "2.0L PHEV"],
        "XC90": ["2.0L Turbo 4-Cyl", "2.0L Turbo/Supercharged 4-Cyl", "2.0L PHEV"],
        "EX30": ["Electric"],
        "EX90": ["Electric"],
    },
}

def get_makes():
    return sorted(VEHICLE_DATA.keys())

def get_models(make):
    return sorted(VEHICLE_DATA.get(make, {}).keys())

def get_engines(make, model):
    return VEHICLE_DATA.get(make, {}).get(model, [])
